/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include <stm32f401re.h>
#include <stm32f401re_rcc.h>  // thêm thư viện RCC cấp xung clock cho GPIO
#include <stm32f401re_gpio.h> // thêm thư viện GPIO


/* ================== Chân phần cứng ================== */

#define BUTTON_PRESS                 0
#define BUTTON_RELEASE               1

//Define LED
#define LED_GPIO_PORT                GPIOA
#define LED_GPIO_PIN                 GPIO_Pin_0
#define LED_GPIO_CLOCK_EN            RCC_AHB1Periph_GPIOA
//Define Button
#define BUZZER_GPIO_PORT             GPIOC
#define BUZZER_GPIO_PIN              GPIO_Pin_9
#define BUZZER_GPIO_CLOCK_EN         RCC_AHB1Periph_GPIOC
//Define Button
#define BUTTON_GPIO_PORT             GPIOB
#define BUTTON_GPIO_PIN              GPIO_Pin_3
#define BUTTON_GPIO_CLOCK_EN         RCC_AHB1Periph_GPIOB

//Khai báo hàm nguyên mẫu
static void mainInit(void);
static void led_Init(void);
static void buttonB2_Init(void);
static void buzzer_Init(void);

static void led_Init(void)
{
	//Khai báo GPIO kiểu structure
	GPIO_InitTypeDef GPIO_InitStructure;
	//Cấp xung Clock hoạt động cho Port A
	RCC_AHB1PeriphClockCmd(LED_GPIO_CLOCK_EN, ENABLE);
	//Cấu hình các thông số cho GPIO: Pin, Mode, Speed, OType, Pu/Pd
	GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	//Khởi tạo các giá trị sử dụng hàm GPIO_Init
	GPIO_Init(LED_GPIO_PORT, &GPIO_InitStructure);
}

static void buzzer_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;

	RCC_AHB1PeriphClockCmd(BUZZER_GPIO_CLOCK_EN, ENABLE);

	GPIO_InitStructure.GPIO_Pin = BUZZER_GPIO_PIN;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;

	GPIO_Init(BUZZER_GPIO_PORT, &GPIO_InitStructure);
}

static void buttonB2_Init(void)
{
	//Khai báo GPIO kiểu structure
	GPIO_InitTypeDef GPIO_InitStructure;
	//Cấp xung Clock hoạt động cho Port B
	RCC_AHB1PeriphClockCmd(BUTTON_GPIO_CLOCK_EN, ENABLE);
	//Cấu hình các thông số cho GPIO: Pin, Mode, Pu/Pd
	//Chọn chân
	GPIO_InitStructure.GPIO_Pin = BUTTON_GPIO_PIN;
	//Chọn Mode Input
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
	// Trạng thái ban đầu kéo lên
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	//Khởi tạo các giá trị cho GPIO
	GPIO_Init(GPIOB, &GPIO_InitStructure);
}

static void mainInit(void)
{
    led_Init();
    buzzer_Init();
    buttonB2_Init();
    // Tuỳ ý đặt trạng thái ban đầu
    GPIO_ResetBits(LED_GPIO_PORT, LED_GPIO_PIN);
    GPIO_ResetBits(BUZZER_GPIO_PORT, BUZZER_GPIO_PIN);
}

int main(void)
{
	// Initialize
	mainInit();

	while(1)
	{
		//Sử dụng hàm GPIO_ReadInputDataBit để đọc trạng thái đầu vào của nút nhấn
		if(GPIO_ReadInputDataBit(BUTTON_GPIO_PORT, BUTTON_GPIO_PIN) == BUTTON_PRESS)
		{
			GPIO_SetBits (LED_GPIO_PORT, LED_GPIO_PIN);        //Turn ON Led
			GPIO_SetBits (BUZZER_GPIO_PORT, BUZZER_GPIO_PIN);  //Turn ON Buzzer
		}
		else
		{
			GPIO_ResetBits (LED_GPIO_PORT, LED_GPIO_PIN);       //Turn OFF Led
			GPIO_ResetBits (BUZZER_GPIO_PORT, BUZZER_GPIO_PIN); //Turn OFF Buzzer
		}
	}
}

