/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdlib.h>

#include "board_config.h"
#include "drivers/gpio.h"
#include "drivers/timebase.h"
#include "periph/led.h"
#include "periph/buzzer.h"
#include "periph/input.h"
#include "gfx/lcd_init.h"
#include "game/ui.h"
#include "game/loop.h"

int main(void){
  Timebase_Init();
  GPIO_EnableAllClocks();

  LED_Init();
  Buzzer_Init();
  Input_Init();
  LCD_Init();

  while(1){
    splash_and_choose_level();
    run_game();
  }
}
